[general]
OPENAI_API_KEY = "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""  # Replace with your actual key
# Placeholder for secrets.toml
